---
- name: Configure NAT
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE
  tags: gateway

- name: Allow LAN Communications
  iptables:
    chain: INPUT
    in_interface: eth1
    jump: ACCEPT
  tags: gateway

- name: Allow WAN Communications
  iptables: 
    chain: INPUT
    in_interface: eth0
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  tags: gateway

- name: Allow Outgoing Communications
  iptables:
    chain: OUTPUT
    jump: ACCEPT
  tags: gateway
